services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /mnt/hdd/docker-volumes/monitoring/data/grafana  # Mount data on HDD