services:
  valheim:
    image: indifferentbroccoli/valheim-server-docker
    container_name: valheim-server
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - '2456:2456/udp'
      - '2457:2457/udp'
    environment:
      PUID: 1000
      PGID: 1000
    env_file:
      - .env
    volumes:
      - /mnt/hdd/docker-volumes/game-servers/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /mnt/hdd/docker-volumes/game-servers/valheim/server:/home/steam/valheim