services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.procfs=/host/proc'   # OS Metrics
      - '--path.sysfs=/host/sys'     # Kernel, hardware and driver metrics
      - '--path.rootfs=/host'        # Disk space and usage
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' # Ignore pseu>
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/host:ro,rslave'